### ISSUE TITLE
virt-build-kata: don't hardcode an IP address

### ISSUE THREAD

**Issue by fidencio** [alicefr/kata-local-ci-setup#4]
Instead of hardcoding an ip address, or even requiring the user to know the VM's IP address, what about enforcing the usage (in the documentation) of the [libvirt-nss](https://libvirt.org/nss.html)?

Having this module installed in the host allows the user to simply `ssh $vm_name`.

**Comment by alicefr** [comment]
@fidencio that's nice, I didn't know it. The hard coded ip was also something I didn't like it. Let me try

**Comment by fidencio** [comment]
> @fidencio that's nice, I didn't know it. The hard coded ip was also something I didn't like it. Let me try

This is how my `/etc/nsswitch.conf` looks like:
```
...
hosts:      files libvirt libvirt_guest mdns4_minimal [NOTFOUND=return] resolve [!UNAVAIL=return] myhostname dns
...
```

**Comment by alicefr** [comment]
I would rather avoid forcing people to use it. You can use also `virsh domifaddr --source lease $domain` to get the same result. Less elegant, but it avoids installing an additional package. We can simply document it as suggested method. You can always put the guest name instead of the ip, and it works. I also put the flag `-n` in order to be able to configure the network.

**Comment by fidencio** [comment]
That totally works for me as well. :-)

**Comment by alicefr** [comment]
The setup works with both either providing and IP or the VM name. Still have to document the usege of libvirt-nss but I'll put as TODO
